[tool.poetry]
name = "opentele"
version = "0.1.0"
description = ""
authors = ["3hx <code@3hx.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
PyQt5-Qt5 = "5.15.2"
telethon
tgcrypto


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
